name: biochemist-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter-book
  - pandas
  - rdkit
  - numpy
  - jupyterlab
  - notebook
  - scipy
  - biopython
  - bokeh
  - nglview
  - seaborn
  - sphinx
  - ipywidgets>8.0
  - nodejs
  - openbabel
  - mdanalysis
  - vina
  - prolif
  - docutils>=0.21
  - pip:
    - icn3dpy
    - rcsbsearchapi
    - pdb2pqr
