name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-book:
    name: Build book
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: biochemist-python
          environment-file: requirements.yaml

      - name: Build the book
        shell: bash -l {0}
        run: |
          jupyter-book build biochemist-python

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: biochemist-python/_build/html